alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: ben.ramsey.dev
    type: PRIMARY
    zone: ramsey.dev
envs:
  - key: APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: prod
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: website
      match:
        path:
          prefix: /
name: ben-ramsey-dev
region: ams
services:
  - build_command: |-
      php bin/console sass:build
      php bin/console asset-map:compile
    environment_slug: php
    github:
      branch: main
      deploy_on_push: true
      repo: ramsey/website
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    name: website
    run_command: heroku-php-apache2 public/
    source_dir: /
