# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.base_url: 'https://ben.ramsey.dev/'
    app.data_dir: '%kernel.project_dir%/data'
    app.data.changed_website_uri: '%app.data_dir%/changed_website_uri.php'
    app.data.openpgp_web_key: '%app.data_dir%/openpgp_web_key.php'
    app.data.webfinger_account: '%app.data_dir%/webfinger_account.php'
    app.service.analytics.secret_key: '%env(resolve:ANALYTICS_SECRET_KEY)%'
    app.service.better_stack.source_token: '%env(resolve:BETTER_STACK_SOURCE_TOKEN)%'
    app.service.league.common_mark.config:
        html_input: 'allow'
        max_nesting_level: 50
        autolink:
            allowed_protocols: ['https', 'http']
            default_protocol: 'https'
        external_link:
            internal_hosts: ['/(^|\.)benramsey\.com$/', '/(^|\.)ramsey\.dev$/']
            open_in_new_window: false
            html_class: 'external'
            nofollow: ''
            noopener: 'external'
            noreferrer: ''
    app.service.plausible.api_token: '%env(resolve:PLAUSIBLE_API_TOKEN)%'
    app.service.plausible.base_uri: 'https://plausible.io/api/'
    app.service.plausible.domains:
        - 'ben.ramsey.dev'
        - 'bram.se'
    app.shortener.base_url: 'https://bram.se/'
    app.shortener.hostname: 'bram.se'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Analytics\AnalyticsService: '@App\Service\Analytics\NoOpProvider'
    App\Service\Blog\PostBodyConverter $markdownToHtmlConverter: '@App\Service\Blog\MarkdownToHtmlConverter'
    App\Service\Blog\PostBodyConverter $postBodyToHtmlConverter: '@App\Service\Blog\PostBodyToHtmlConverter'
    Devarts\PlausiblePHP\PlausibleAPI:
        arguments:
            - '%app.service.plausible.api_token%'
            - '%app.service.plausible.base_uri%'
    GeoIp2\ProviderInterface: '@geoip2.database.default_reader'
    Laminas\Diactoros\UriFactory: ~
    League\CommonMark\ConverterInterface: '@League\CommonMark\MarkdownConverter'
    League\CommonMark\Extension\:
        resource: '../vendor/league/commonmark/src/Extension/'
    League\CommonMark\Environment\Environment:
        arguments: ['%app.service.league.common_mark.config%']
        calls:
            - addExtension: ['@League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension']
            - addExtension: ['@League\CommonMark\Extension\Attributes\AttributesExtension']
            - addExtension: ['@League\CommonMark\Extension\Autolink\AutolinkExtension']
            - addExtension: ['@League\CommonMark\Extension\DescriptionList\DescriptionListExtension']
            - addExtension: ['@League\CommonMark\Extension\DisallowedRawHtml\DisallowedRawHtmlExtension']
            - addExtension: ['@League\CommonMark\Extension\ExternalLink\ExternalLinkExtension']
            - addExtension: ['@League\CommonMark\Extension\Footnote\FootnoteExtension']
            - addExtension: ['@League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension']
            - addExtension: ['@League\CommonMark\Extension\Strikethrough\StrikethroughExtension']
            - addExtension: ['@League\CommonMark\Extension\Table\TableExtension']
            - addExtension: ['@League\CommonMark\Extension\SmartPunct\SmartPunctExtension']
    League\CommonMark\Environment\EnvironmentInterface: '@League\CommonMark\Environment\Environment'
    League\CommonMark\MarkdownConverter: ~
    Logtail\Monolog\LogtailHandler:
        arguments:
            - '%app.service.better_stack.source_token%'
            - 'info'
    PhpExtended\Email\MailboxListParser: ~
    PhpExtended\Email\MailboxListParserInterface: '@PhpExtended\Email\MailboxListParser'
    Psr\Clock\ClockInterface $monotonicClock: '@Symfony\Component\Clock\MonotonicClock'
    Psr\Clock\ClockInterface: '@Symfony\Component\Clock\NativeClock'
    Psr\Http\Message\UriFactoryInterface: '@Laminas\Diactoros\UriFactory'
    Symfony\Component\Clock\MonotonicClock: ~
    Symfony\Component\Clock\NativeClock: ~
    Symfony\Component\Filesystem\Filesystem: ~
    Symfony\Component\Finder\Finder: ~
    Webuni\FrontMatter\FrontMatterInterface:
        factory: ['Webuni\FrontMatter\FrontMatterChain', 'create']

when@test: &services_test
    parameters:
        app.base_url: 'https://localhost/'
        app.service.plausible.domains:
            - 'not-a-domain-that-should-be-used-in-a-test.example.com'
        app.shortener.base_url: 'https://localhost/su/'

    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\DataFixtures\:
            resource: '../tests/DataFixtures'
        
        App\Twig\Extension:
            public: true
        App\Service\Analytics\AnalyticsService: '@App\Service\Analytics\NoOpProvider'
        GeoIp2\ProviderInterface: '@App\Service\GeoIp2\NoOpProvider'

when@test_no_db: *services_test

when@dev:
    parameters:
        app.base_url: 'https://localhost:8000/'
        app.shortener.base_url: 'https://localhost:8000/su/'

    services:
        App\Service\Analytics\AnalyticsService: '@App\Service\Analytics\NoOpProvider'
        GeoIp2\ProviderInterface: '@App\Service\GeoIp2\NoOpProvider'
