# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.data_dir: '%kernel.project_dir%/data'
    app.data.changed_website_uri: '%app.data_dir%/changed_website_uri.php'
    app.data.openpgp_web_key: '%app.data_dir%/openpgp_web_key.php'
    app.data.webfinger_account: '%app.data_dir%/webfinger_account.php'

    app.shortener.base_url: 'https://bram.se/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Laminas\Diactoros\UriFactory: ~
    Psr\Http\Message\UriFactoryInterface: '@Laminas\Diactoros\UriFactory'

when@test:
    parameters:
        app.shortener.base_url: 'https://localhost/su/'

    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\DataFixtures\:
            resource: '../tests/DataFixtures'

when@dev:
    parameters:
        app.shortener.base_url: 'https://localhost:8000/su/'
