# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "Continuous Integration"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request_target:
    branches:
      - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  APP_ENV: "test"

jobs:
  coding-standards:
    name: "Coding standards"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.31.1"
        with:
          php-version: "latest"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Check syntax (php-parallel-lint)"
        run: "composer lint:syntax"

      - name: "Check coding standards (PHP_CodeSniffer)"
        run: "composer lint:style"

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.31.1"
        with:
          php-version: "latest"
          coverage: "none"
          ini-values: "memory_limit=-1"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Statically analyze code (PHPStan)"
        run: "composer analyze:phpstan"

  tests:
    name: "Tests"
    needs: ["coding-standards", "static-analysis"]
    runs-on: "ubuntu-latest"

    env:
      DATABASE_URL: "postgresql://app:9b487983153e2a5a9be25c8d9788e6eb@127.0.0.1:5432/app_test?serverVersion=16&charset=utf8"

    services:
      postgres:
        image: "postgres:16"
        env:
          POSTGRES_PASSWORD: "9b487983153e2a5a9be25c8d9788e6eb"
          POSTGRES_USER: "app"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.7"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.31.1"
        with:
          php-version: "latest"
          coverage: "xdebug"
          ini-values: "memory_limit=-1"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Set up database for testing"
        run: |
          composer test:db:setup
          composer test:db:fixtures

      - name: "Build Sass"
        run: "php bin/console sass:build"

      - name: "Run unit tests (PHPUnit)"
        run: "composer test:coverage:ci"

      - name: "Publish coverage report to Codecov"
        uses: "codecov/codecov-action@v4.5.0"
        with:
          fail_ci_if_error: true
          token: "${{ secrets.CODECOV_TOKEN }}"
