# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "Continuous Integration"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  APP_ENV: test

jobs:
  coding-standards:
    name: "Coding standards"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.4"
        with:
          php-version: "latest"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Check syntax (php-parallel-lint)"
        run: "composer lint:syntax"

      - name: "Check coding standards (PHP_CodeSniffer)"
        run: "composer lint:style"

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.4"
        with:
          php-version: "latest"
          coverage: "none"
          ini-values: "memory_limit=-1"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Statically analyze code (PHPStan)"
        run: "composer analyze:phpstan"

  tests:
    name: "Tests"
    needs: ["coding-standards", "static-analysis"]
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.1.5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.30.4"
        with:
          php-version: "latest"
          coverage: "xdebug"
          ini-values: "memory_limit=-1"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@3.0.0"

      - name: "Build Sass"
        run: "php bin/console sass:build"

      - name: "Run unit tests (PHPUnit)"
        run: "composer test:coverage:ci"

      - name: "Publish coverage report to Codecov"
        uses: "codecov/codecov-action@v4.3.1"
